name: Build DiBris for Development

on:
  push:
    branches: [ develop ]
    paths: 
      - 'DiBris/**'
      - '.github/workflows/develop.yml'
  pull_request:
    branches: [ develop ]
    paths:  
      - 'DiBris/**'
      - '.github/workflows/develop.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Get SiraRef
      env:
        FILES_URL: ${{ secrets.SDEPS_URL }}
      run: wget --no-check-certificate "$FILES_URL" -q -O xfs.zip
    - name: Extract SiraRef
      run: unzip -q -n xfs.zip -d ./Refs
    - name: Build
      id: Build
      env: 
        FrameworkPathOverride: /usr/lib/mono/4.7.2-api
      run: dotnet build --configuration Debug
    - name: Echo Filename
      run: echo "$BUILDTEXT ($ASSEMBLYNAME)"
      env:
        BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
        ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
