name: Build and Deploy DiBris

on:
  push:
    branches: [ main ]
    paths: 
      - 'DiBris/**'
      - '.github/workflows/main.yml'
  pull_request:
    branches: [ main ]
    paths:  
      - 'DiBris/**'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Get SiraRef
      env:
        FILES_URL: ${{ secrets.SDEPS_URL }}
      run: wget --no-check-certificate "$FILES_URL" -q -O xfs.zip
    - name: Extract SiraRef
      run: unzip -q -n xfs.zip -d ./Refs
    - name: Build
      id: Build
      env: 
        FrameworkPathOverride: /usr/lib/mono/4.7.2-api
      run: dotnet build --configuration Release
    - name: Echo Filename
      run: echo "$BUILDTEXT ($ASSEMBLYNAME)"
      env:
        BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
        ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.Build.outputs.filename }}
        path: ./DiBris/bin/Release/Final
    - name: CopyPDB
      working-directory: ./DiBris/bin/Release
      run: cp ${{ steps.Build.outputs.assemblyname }}.pdb Final/Plugins/${{ steps.Build.outputs.assemblyname }}.pdb
    - name: Upload Artifact With PDB
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.Build.outputs.filename }}_WithPDB
        path: ./DiBris/bin/Release/Final
